name: Synchronize JIRA
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types:
      [
        opened,
        reopened,
        synchronize,
        review_requested,
        review_request_removed,
        closed
      ]

jobs:
  transition-jira-tickets:
    runs-on: ubuntu-latest
    name: Synchronize JIRA tickets of PR
    steps:
      - name: Synchronized JIRA tickets based on PR status
        uses: SonarSource/sync-jira-github-action@master
        with:
          github-token: ${{ secrets.GH_ORG_TOKEN }}
          jira-login: ${{ secrets.JIRA_LOGIN }}
          jira-password: ${{ secrets.JIRA_PASSWORD }}
          jira-project: SC
          jira-url: https://sonarsource-jira-test.valiantys.net
